name: unit-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install -y libboost-all-dev
      - name: Build
        run: |
          ./autogen.sh
          ./configure CXX=${{ matrix.compiler }}
          make
      - name: Test
        run: make test
